blueprint:
  name: IKEA BILRESA Scroll Wheel – Single Group
  description: >
    Map one Bilresa group (3 event entities) to a role: **light** or **media**.
    Create one automation instance per group you want to activate.

    **Light role:**
    - Single press: toggle light
    - Double press: cycle 3 color_temp_kelvin presets
    - Scroll right/left: brightness up/down (scaled by notch count)

    **Media role:**
    - Single press: play/pause
    - Double press: next track
    - Scroll right/left: volume up/down (scaled by notch count)

  domain: automation
  source_url: https://github.com/yourname/ha-bilresa-blueprints

  input:

    # ═══════════════════════════════════════════════
    # GROUP ROLE & EVENTS
    # ═══════════════════════════════════════════════

    group_role:
      name: "Role"
      description: "What this group controls."
      default: light
      selector:
        select:
          options:
            - label: "Light"
              value: light
            - label: "Media player"
              value: media

    scroll_right_event:
      name: "Scroll right event entity"
      description: "e.g. event.bilresa_scroll_wheel_button_1"
      selector:
        entity:
          domain: event

    scroll_left_event:
      name: "Scroll left event entity"
      description: "e.g. event.bilresa_scroll_wheel_button_2"
      selector:
        entity:
          domain: event

    press_event:
      name: "Press event entity"
      description: "e.g. event.bilresa_scroll_wheel_button_3"
      selector:
        entity:
          domain: event

    # ═══════════════════════════════════════════════
    # TARGETS
    # ═══════════════════════════════════════════════

    target_light:
      name: "Target light"
      description: "Required when role = light. Ignored otherwise."
      default: ""
      selector:
        entity:
          domain: light

    target_media:
      name: "Target media player"
      description: "Required when role = media. Ignored otherwise."
      default: ""
      selector:
        entity:
          domain: media_player

    # ═══════════════════════════════════════════════
    # SHARED TUNING
    # ═══════════════════════════════════════════════

    brightness_step_pct:
      name: Brightness step per notch (%)
      default: 5
      selector:
        number:
          min: 1
          max: 50
          step: 1
          unit_of_measurement: "%"

    volume_step:
      name: Volume step per notch (0–1)
      description: "0.03 ≈ 3% per notch"
      default: 0.03
      selector:
        number:
          min: 0.01
          max: 0.2
          step: 0.01

    ct_preset_1_kelvin:
      name: CT preset 1 (Kelvin)
      default: 2700
      selector:
        number:
          min: 1500
          max: 9000
          step: 50
          unit_of_measurement: K

    ct_preset_2_kelvin:
      name: CT preset 2 (Kelvin)
      default: 3500
      selector:
        number:
          min: 1500
          max: 9000
          step: 50
          unit_of_measurement: K

    ct_preset_3_kelvin:
      name: CT preset 3 (Kelvin)
      default: 5000
      selector:
        number:
          min: 1500
          max: 9000
          step: 50
          unit_of_measurement: K

    ct_match_tolerance_kelvin:
      name: CT match tolerance (Kelvin)
      description: "How close the current CT must be to a preset to count as 'on that preset'."
      default: 200
      selector:
        number:
          min: 50
          max: 1000
          step: 50
          unit_of_measurement: K

mode: restart
max_exceeded: silent

variables:
  role:         !input group_role
  ev_right:     !input scroll_right_event
  ev_left:      !input scroll_left_event
  ev_press:     !input press_event
  light_entity: !input target_light
  media_entity: !input target_media
  step_bri_pct: !input brightness_step_pct
  step_vol:     !input volume_step
  ct1:          !input ct_preset_1_kelvin
  ct2:          !input ct_preset_2_kelvin
  ct3:          !input ct_preset_3_kelvin
  ct_tol:       !input ct_match_tolerance_kelvin

trigger:
  - platform: state
    entity_id: !input scroll_right_event
  - platform: state
    entity_id: !input scroll_left_event
  - platform: state
    entity_id: !input press_event

action:

  # ── Step 1: resolve runtime event fields ─────────────────────────────────
  - variables:
      ev_type: >
        {{ trigger.to_state.attributes.event_type
           | default(state_attr(trigger.entity_id, 'event_type'))
           | default('') }}
      count: >
        {{ trigger.to_state.attributes.totalNumberOfPressesCounted
           | default(state_attr(trigger.entity_id, 'totalNumberOfPressesCounted'))
           | default(1) | int(1) }}

  # ── Step 2: compute next CT preset (light role only) ─────────────────────
  - variables:
      current_ct_k: >
        {% set k = state_attr(light_entity, 'color_temp_kelvin') %}
        {% if k is not none %}
          {{ k | int }}
        {% else %}
          {% set m = state_attr(light_entity, 'color_temp') %}
          {% if m is not none and (m | int) > 0 %}
            {{ (1000000 / (m | float)) | round(0) | int }}
          {% else %}
            0
          {% endif %}
        {% endif %}
      next_ct_k: >
        {% set k = current_ct_k | int(0) %}
        {% set t = ct_tol | int(200) %}
        {% set p1 = ct1 | int %}
        {% set p2 = ct2 | int %}
        {% set p3 = ct3 | int %}
        {% if k > 0 and (k - p1) | abs <= t %}
          {{ p2 }}
        {% elif k > 0 and (k - p2) | abs <= t %}
          {{ p3 }}
        {% elif k > 0 and (k - p3) | abs <= t %}
          {{ p1 }}
        {% else %}
          {{ p1 }}
        {% endif %}

  # ── Step 3: route to the correct action ──────────────────────────────────
  - choose:

      # ── LIGHT ROLE ────────────────────────────────────────────────────────

      - conditions: "{{ role == 'light' and trigger.entity_id == ev_press and ev_type == 'multi_press_1' }}"
        sequence:
          - service: light.toggle
            target:
              entity_id: "{{ light_entity }}"

      - conditions: "{{ role == 'light' and trigger.entity_id == ev_press and ev_type == 'multi_press_2' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ light_entity }}"
            data:
              color_temp_kelvin: "{{ next_ct_k }}"

      - conditions: "{{ role == 'light' and trigger.entity_id == ev_right and ev_type.startswith('multi_press_') }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ light_entity }}"
            data:
              brightness_step_pct: "{{ (step_bri_pct | int(5)) * count }}"

      - conditions: "{{ role == 'light' and trigger.entity_id == ev_left and ev_type.startswith('multi_press_') }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ light_entity }}"
            data:
              brightness_step_pct: "{{ 0 - (step_bri_pct | int(5)) * count }}"

      # ── MEDIA ROLE ────────────────────────────────────────────────────────

      - conditions: "{{ role == 'media' and trigger.entity_id == ev_press and ev_type == 'multi_press_1' }}"
        sequence:
          - service: media_player.media_play_pause
            target:
              entity_id: "{{ media_entity }}"

      - conditions: "{{ role == 'media' and trigger.entity_id == ev_press and ev_type == 'multi_press_2' }}"
        sequence:
          - service: media_player.media_next_track
            target:
              entity_id: "{{ media_entity }}"

      - conditions: "{{ role == 'media' and trigger.entity_id == ev_right and ev_type.startswith('multi_press_') }}"
        sequence:
          - variables:
              old_vol: "{{ state_attr(media_entity, 'volume_level') | float(0.3) }}"
              delta:   "{{ (step_vol | float(0.03)) * count }}"
              new_vol: >
                {% set v = old_vol + delta %}
                {% if v < 0 %} 0
                {% elif v > 1 %} 1
                {% else %} {{ v }}
                {% endif %}
          - service: media_player.volume_set
            target:
              entity_id: "{{ media_entity }}"
            data:
              volume_level: "{{ new_vol }}"

      - conditions: "{{ role == 'media' and trigger.entity_id == ev_left and ev_type.startswith('multi_press_') }}"
        sequence:
          - variables:
              old_vol: "{{ state_attr(media_entity, 'volume_level') | float(0.3) }}"
              delta:   "{{ (step_vol | float(0.03)) * count }}"
              new_vol: >
                {% set v = old_vol - delta %}
                {% if v < 0 %} 0
                {% elif v > 1 %} 1
                {% else %} {{ v }}
                {% endif %}
          - service: media_player.volume_set
            target:
              entity_id: "{{ media_entity }}"
            data:
              volume_level: "{{ new_vol }}"
